version: '3'
services:
  grafana:
    image: grafana/grafana:7.4.3
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/conprof-datasource
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - COMPOSE_INTERACTIVE_NO_CLI=1
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
volumes:
  grafana-storage:
